# Generated by Django 3.1.7 on 2021-09-07 11:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Complexion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genotype', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='NextClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SurName', models.CharField(max_length=150)),
                ('FirstName', models.CharField(max_length=150)),
                ('LastName', models.CharField(blank=True, max_length=150)),
                ('Birth_date', models.DateField()),
                ('Weight', models.FloatField(blank=True)),
                ('Height', models.FloatField(blank=True)),
                ('Local_government_Area', models.CharField(blank=True, max_length=200)),
                ('Name_of_parent_or_guardian', models.CharField(max_length=250)),
                ('Address_of_parent_or_guardian', models.TextField()),
                ('Phone_number', models.IntegerField()),
                ('In_case_of_emergency_call', models.IntegerField()),
                ('E_mail', models.EmailField(blank=True, max_length=254)),
                ('Admission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Admission_number', models.CharField(blank=True, max_length=30)),
                ('profile_picture', models.ImageField(default='primus.jpg', upload_to='profile_pics')),
                ('Blood_group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolProfile.bloodgroup')),
                ('Religion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolProfile.religion')),
                ('Sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolProfile.sex')),
                ('State_of_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolProfile.state')),
                ('complexion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolProfile.complexion')),
                ('genotype', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolProfile.genotype')),
                ('next_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolProfile.nextclass')),
                ('previous_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolProfile.previousclass')),
            ],
        ),
    ]
