# Generated by Django 3.1.7 on 2021-09-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolProfile', '0002_auto_20210908_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
