# Generated by Django 3.1.7 on 2021-09-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolProfile', '0003_auto_20210909_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_Pics'),
        ),
    ]
