# Generated by Django 3.1.7 on 2021-09-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolProfile', '0004_auto_20210909_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolPrefect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SurName', models.CharField(max_length=150)),
                ('FirstName', models.CharField(max_length=150)),
                ('OtherNames', models.CharField(blank=True, max_length=200)),
                ('Office', models.CharField(max_length=100)),
                ('WiseQuote', models.TextField(blank=True)),
                ('Picture', models.ImageField(upload_to='profile_pics')),
                ('BestSubject', models.CharField(max_length=20)),
                ('Class', models.CharField(max_length=10)),
                ('Career', models.CharField(max_length=200)),
                ('FavouriteTeacher', models.CharField(blank=True, max_length=200)),
                ('RoleModel', models.TextField(blank=True)),
                ('Skills', models.TextField(blank=True)),
                ('FavouriteFood', models.CharField(blank=True, max_length=200)),
                ('FavouriteMusic', models.TextField(blank=True)),
                ('FavouriteTvShows', models.TextField(blank=True)),
                ('Department', models.CharField(max_length=10)),
                ('Dislikes', models.TextField(blank=True)),
                ('YearInducted', models.DateField()),
            ],
        ),
    ]
