# Generated by Django 3.1.7 on 2021-09-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolProfile', '0005_dates_schoolprefect'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolPrefect',
        ),
    ]
